C CALCOLO DAL FATTORIALE DI NMAX NUMERI

	PROGRAM FATTORIALE
	REAL*8 N, NMAX, FATT
	WRITE(*,*)'CALCOLO I FATTORIALI DEI PRIMI N NUMERI; INSERISCI IL
	* VALORE DI N:'
	READ(*,*)NMAX
	FATT=1
	DO N=1,NMAX
	FATT=FATT*N 
	WRITE(*,*) 'IL FATTORIALE DI',N, ' E''',FATT
	END DO
	END