C Date due matrici di ordine n calcolare la matrice prodotto.
	
	PROGRAM PRODMAT
	INTEGER N, I, J, K, H
	REAL A(100, 100), B(100, 100), P(100, 100)
	WRITE(*,*)'INSERISCI L''ORDINE DELLE DUE MATRICI: '
	READ(*,*)N
	
C INSERIMENTO DELLA PRIMA MATRICE
	WRITE(*,*)'INSERISCI LE COMPONENTI DELLA PRIMA MATRICE: '
	READ(*,*)((A(I, J), J=1, N), I=1, N)

C SCRIVIAMO LA PRIMA MATRICE:
	WRITE(*,*)'LA MATRICE A E'':'
	DO I=1, N
	WRITE(*,*)(A(I,J), J=1, N)
	ENDDO

C INSERIMENTO DELLA SECONDA MATRICE
	WRITE(*,*)'INSERISCI LE COMPONENTI DELLA SECONDA MATRICE: '
	READ(*,*)((B(I, J), J=1, N), I=1, N)

C SCRIVIAMO LA SECONDA MATRICE:
	WRITE(*,*)'LA MATRICE B E'':'
	DO I=1, N
	WRITE(*,*)(B(I,J), J=1, N)
	ENDDO

C MOLTIPLICHIAMO LE DUE MATRICI 
	DO I=1,N
	DO J=1,N
	P(I,J)=0
	DO K=1,N
	P(I,J)=P(I,J)+A(I,K)*B(K,J)
	END DO
	END DO
	END DO
	WRITE(*,*) 'LA MATRICE PRODOTTO E'': '
	DO I=1,N
	WRITE(*,*) (P(I,J),J=1,N)
	WRITE(*,*)
	END DO
	END