C Date due matrici di ordine n calcolare la matrice somma.

	PROGRAM SOMMAT
	INTEGER NMAX, MMAX, N, M, I, J
	PARAMETER(NMAX=50, MMAX=50)
	REAL A(NMAX, MMAX), B(NMAX, MMAX), S(NMAX, MMAX)
	WRITE(*,*)'INSERISCI IL NUMERO DI RIGHE:'
	READ(*,*)N
	WRITE(*,*)'INSERISCI IL NUMERO DI COLONNE:'
	READ(*,*)M
C INSERIMENTO DELLA PRIMA MATRICE
	DO I=1, N
	DO J=1, M
	WRITE(*,*)'INSERISCI IL VALORE DELLE COMPONENTI DI A', I,J
	READ(*,*) A(I, J)
	ENDDO
	ENDDO

C SCRIVIAMO LA PRIMA MATRICE:
	WRITE(*,*)'LA MATRICE A E'':'
	DO I=1, N
	WRITE(*,*)(A(I,J), J=1, M)
	ENDDO

C INSERIMENTO DELLA SECONDA MATRICE
	DO I=1, N
	DO J=1, M
	WRITE(*,*)'INSERISCI IL VALORE DELLE COMPONENTI DI B', I,J
	READ(*,*) B(I, J)
	ENDDO
	ENDDO

C SCRIVIAMO LA SECONDA MATRICE:
	WRITE(*,*)'LA MATRICE B E'':'
	DO I=1, N
	WRITE(*,*)(B(I,J), J=1, M)
	ENDDO

C SOMMIAMO LE DUE MATRICI 
	S(I,J)=0
	DO I=1,N
	DO J=1,M
	S(I,J)=A(I,J)+B(I,J)
	END DO
	END DO
	WRITE(*,*)'LA SOMMA DELLE DUE MATRICI INSERITE E'':'
	DO I=1,N
	WRITE(*,*)(S(I,J),J=1,M)
	WRITE(*,*)
	ENDDO 
	END