C TROVARE IL MASSIMO O IL MINIMO DI UN INSIEME DI NUMERI

	PROGRAM MAX_MIN
	REAL X(100),M, A
	INTEGER I,N
	WRITE(*,*)'QUANTI NUMERI VUOI INSERIRE?'
	READ(*,*)N
	WRITE(*,*)'INSERIMENTO DEI NUMERI:'
	DO I=1,N
	READ(*,*) X(I)
	END DO
	WRITE(*,*)'I NUMERI SONO:'
	DO I=1,N
	WRITE(*,*) X(I)
	END DO
	
C CALCOLO DEL MASSIMO
      M=0
	DO I=1,N
	IF (ABS(X(I)).GT.M) THEN
	M=ABS(X(I))
	END IF
	END DO
	WRITE(*,*) 'IL MASSIMO TRA QUESTI NUMERI E''',M

C CALCOLO DEL MINIMO	
	A=1000
 	DO I=1,N
	IF (ABS(X(I)).LT.A) THEN
	A=ABS(X(I))
	END IF 
	END DO
      WRITE(*,*) 'IL MINIMO TRA QUESTI NUMERI E''',A
      END