C	QUESTO PROGRAMMA ESEGUE LA MEDIA DI N NUMERI

      PROGRAM MEDIA
	INTEGER N
	REAL M,X(100),I,S
	WRITE(*,*)'QUANTI NUMERI VUOI INSERIRE?'
	READ(*,*)N
	WRITE(*,*)'INSERIMENTO DE I', N, ' NUMERI: '
	DO I=1,N
	READ(*,*) X(I)
	ENDDO

C ESEGUIAMO LA SOMMA DEI NUMERI
	
	S=0
	DO I=1,N
	S=S+X(I)
	END DO
	M=S/N
	WRITE(*,*) 'La loro media e''', M
	END